# Generated by Django 5.2 on 2025-05-06 10:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_id', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='College Name')),
                ('website', models.URLField(validators=[django.core.validators.URLValidator()], verbose_name='Website')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('address', models.TextField(verbose_name='Address')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='college_logos/', verbose_name='College Logo')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='college_images/')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='educationpioneer.college')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=100)),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eligibility', models.TextField()),
                ('age_limit', models.IntegerField()),
                ('eligibility_info', models.TextField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='educationpioneer.college')),
            ],
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['email'], name='educationpi_email_d57d81_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['college_id'], name='educationpi_college_5dba07_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['name'], name='educationpi_name_ae1ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['district'], name='educationpi_distric_bec1c9_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['state'], name='educationpi_state_3abbe8_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['country'], name='educationpi_country_2bd74c_idx'),
        ),
    ]
