# Generated by Django 5.2 on 2025-05-06 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationpioneer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='college',
            name='educationpi_email_d57d81_idx',
        ),
        migrations.RemoveIndex(
            model_name='college',
            name='educationpi_college_5dba07_idx',
        ),
        migrations.RemoveIndex(
            model_name='college',
            name='educationpi_name_ae1ad9_idx',
        ),
        migrations.RemoveIndex(
            model_name='college',
            name='educationpi_distric_bec1c9_idx',
        ),
        migrations.RemoveIndex(
            model_name='college',
            name='educationpi_state_3abbe8_idx',
        ),
        migrations.RemoveIndex(
            model_name='college',
            name='educationpi_country_2bd74c_idx',
        ),
        migrations.RemoveField(
            model_name='college',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='college',
            name='user',
        ),
        migrations.AddField(
            model_name='college',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationpioneer.college'),
        ),
    ]
