# Generated by Django 5.2 on 2025-05-07 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationpioneer', '0005_collegeapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationpioneer.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationpioneer.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationpioneer.student')),
            ],
            options={
                'unique_together': {('student', 'college', 'course')},
            },
        ),
        migrations.DeleteModel(
            name='CollegeApplication',
        ),
    ]
