# Generated by Django 5.2 on 2025-05-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educationpioneer', '0006_application_delete_collegeapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applied_date',
            new_name='applied_at',
        ),
    ]
