# Generated by Django 5.2 on 2025-05-14 10:30

import educationpioneer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationpioneer', '0007_rename_applied_date_application_applied_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('web_details', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=educationpioneer.models.agent_profile_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
