# Generated by Django 5.2 on 2025-05-07 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationpioneer', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationpioneer.college')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationpioneer.student')),
            ],
            options={
                'unique_together': {('student', 'college')},
            },
        ),
    ]
