# Generated by Django 5.1.6 on 2025-05-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationpioneer', '0009_alter_agent_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='student_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='application',
            name='student_district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='application',
            name='student_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
    ]
