# Generated by Django 5.1.6 on 2025-06-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationpioneer', '0011_studentregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
