# Generated by Django 5.1.6 on 2025-06-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationpioneer', '0014_course_created_at_course_total_semesters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About College'),
        ),
    ]
